web:
 image: wordpress
 volumes:
  - ./themes:/var/www/html/wp-content/themes/
 links:
  - mysql
 environment:
  - WORDPRESS_DB_PASSWORD=password
 ports:
  - "127.0.0.1:8889:80"
mysql:
 image: mysql:latest
 environment:
  - MYSQL_ROOT_PASSWORD=password
  - MYSQL_DATABASE=wp-local-db
