web:
 image: wordpress
 volumes:
  - ./themes:/var/www/html/wp-content/themes/
  - ./plugins:/var/www/html/wp-content/plugins/
 links:
  - mariadb:mysql
 environment:
  - WORDPRESS_DB_PASSWORD=password
 ports:
  - "127.0.0.1:8889:80"
mariadb:
 image: mariadb:latest
 environment:
  - MYSQL_ROOT_PASSWORD=password
  - MYSQL_DATABASE=matrix-wp-local-db
